language: node_js
node_js: 10
sudo: false
cache:
- node_modules
- yarn
script:
- set -e
- yarn lint
- yarn test-ci
- yarn tsc --noEmit
- |
  if [[ $TRAVIS_BRANCH == "master" ]]; then
    yarn build
    BUILT_TESTS=1 yarn built-test-ci
  fi
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: s3
  access_key_id: AKIAV7MGHX5ZQA5FHIE2
  secret_access_key:
    secure: dGJPf5aU9EwvM2xnO/u6ner8MPlN3OHpIy/4/DaS0hjQ1OtE4qgV1D5bY9NMKZGvgcrCH2kYVWJThLB3XMDViWYhYR/4goXB3IrMPLF+vjV6Tm3/iNoHlEZyNAxNXkPPbLg4RAqEKoNn2wp6R9P4k3/jh6plYPrwuurdq0pgr4cc/quWSCNaopzca0CG4jUuOAgHjHiI82A5eCieF6RyhYm75wgHzTsT8v6kZHZ/EpoC0s6BpbUzhQQStZrI+s4cLQ5r6iQc5DBVvsvEX8WnHiku/ftFvdxqa/Ymtv9MJqiv9qh8uclTXWZAtVpvhMtb+D4DR3v9f+fAwFKnhuxL9k450Y2gdCNbOW3pplzz4LFSx1kGgpZv2UTBzKe3D25rlZRKJKaTCEkUPsxZS4YXEnEGjIJW64q9u9uk2gRiTDQXyCeNmiGdjlaK55b2QXub7Ew6i7849QA54eK/ijFNKyRAUxLci0tPP4Kwyhwxm6AddFqftcualrwJ32YKmuMvwCppxOXhsAdnc395uezzJg0PHTP7hxaeK3uJbC1gV6kvOaEZQTS8aar9fCSXIhufuFM9mwDIRj8lHq8s40z5AcdtVhd+DU7Eh68VAyMSX4LRbRMENT4QX5aQT11ycHzqvM8vPm/wRtt7e5mrk2tDo5wGPfVpHHpSy/4Wga4puPw=
  bucket: jbrowse.org
  local-dir: packages/jbrowse-web/build
  upload-dir: code/jb2/alpha/$TRAVIS_COMMIT
  acl: public_read
  on:
    repo: GMOD/jbrowse-components
